DROP TABLE IF EXISTS USERS;

CREATE TABLE USERS (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT, password TEXT, carboncost FLOAT carbonsaved FLOAT, history TEXT);

CREATE TABLE RECIPES (id INTEGER PRIMARY KEY AUTOINCREMENT, ingredients TEXT, carboncost FLOAT, carbonsaved FLOAT)