DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS INGREDIENTS;

CREATE TABLE USERS (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT, password TEXT, carboncost FLOAT, carbonsaved FLOAT, history TEXT);
CREATE TABLE FRIENDS (id INTEGER PRIMARY KEY AUTOINCREMENT, userid INTEGER, name TEXT);

--CREATE TABLE RECIPES (id INTEGER PRIMARY KEY AUTOINCREMENT, ingredients TEXT, carboncost FLOAT, carbonsaved FLOAT)

CREATE TABLE INGREDIENTS (id INTEGER PRIMARY KEY AUTOINCREMENT, foodtype TEXT, foodname TEXT, quantity FLOAT, carboncost FLOAT, userid INTEGER, FOREIGN KEY(userid) REFERENCES USERS(id));